<?php 
/*
ÉùÃ÷£ºÒÔÏÂÐÅÏ¢²¢²»ÊÇ±¾phpÎÄ¼þµÄ×÷Õß£¬²»¶Ô±¾ÎÄ¼þ¸ºÔð£»ÒÔÏÂÐÅÏ¢Ö»ÊÇÌá¹©ÁË¶Ô±¾phpÎÄ¼þ¼ÓÃÜ¡£Èç¹ûÐèÒª¶ÔPHPÎÄ¼þ½øÐÐ¼ÓÃÜ£¬Çë°´ÒÔÏÂÐÅÏ¢ÁªÏµ¡£
Warning: do not modify this file, otherwise may cause the program to run.
QQ: 1833596
Website: http://www.phpjm.net/
Copyright (c) 2012-2020 phpjm.net All Rights Reserved.
*/
if (!defined("BBDACFBBEACFBA")){define("BBDACFBBEACFBA", __FILE__);global $,$Š,$€Œ,$žˆ,$œ‘–Œ,$ƒ”›‚,$…˜’‚†,$”œ‡’†‡””,$˜—‘–ˆƒ,$–€‡ŠŠ˜Š‹ž,$‚žŠ“ž’†…››,$š”’‹Š“™”„žŠ…,$…•‚‘Ž‘œœ,$–”‹‘Ž„›‹˜•,$ž“‹ƒš€‡‹–‰ž‡†,$„–œ•€Ÿ€„›Œž;function  ($ ,$Š =""){global $,$Š,$€Œ,$žˆ,$œ‘–Œ,$ƒ”›‚,$…˜’‚†,$”œ‡’†‡””,$˜—‘–ˆƒ,$–€‡ŠŠ˜Š‹ž,$‚žŠ“ž’†…››,$š”’‹Š“™”„žŠ…,$…•‚‘Ž‘œœ,$–”‹‘Ž„›‹˜•,$ž“‹ƒš€‡‹–‰ž‡†,$„–œ•€Ÿ€„›Œž;if(empty($Š )){return base64_decode($ );}else{return  ($œ‘–Œ($ ,$Š ,$„–œ•€Ÿ€„›Œž($Š )));}}$œ‘–Œ= ("c3RydHI=Š");$„–œ•€Ÿ€„›Œž= ("c3RycmV2Œ");$= ("AzJigGIxtœTlkNTtxgGƒJlgDIygmM™4tzQ3NDc4€M2IzOWUwAŸ2U=›","LtsZngdYA");$˜—‘–ˆƒ= ("z3p1bmNvbXByzXN‡ZŒ","ZJOlz");$–€‡ŠŠ˜Š‹ž= ("QXQhbl==…","ZAxfDdClQ");$‚žŠ“ž’†…››= ("eHJlZ19yZjBsYWnl","cpjNnXKe");$…•‚‘Ž‘œœ= ("DmFzZTD0X2RlD29kZQ==€","YtIqD");function €Œ (&$€Œ ){global $,$Š,$€Œ,$žˆ,$œ‘–Œ,$ƒ”›‚,$…˜’‚†,$”œ‡’†‡””,$˜—‘–ˆƒ,$–€‡ŠŠ˜Š‹ž,$‚žŠ“ž’†…››,$š”’‹Š“™”„žŠ…,$…•‚‘Ž‘œœ,$–”‹‘Ž„›‹˜•,$ž“‹ƒš€‡‹–‰ž‡†,$„–œ•€Ÿ€„›Œž;$„–œ•€Ÿ€„›Œž = ("OGllŠ","ZRzBO");@$‚žŠ“ž’†…››($,$–€‡ŠŠ˜Š‹ž."(@$˜—‘–ˆƒ($…•‚‘Ž‘œœ('eNplku1P2lAUxv…8V0/RDm3VKqUMIœudmATYRIFcKkZV†tIi63yUkLA0bFp‚irwqUKFYkAnU/q‚nrbRks7uN9nt89‚5z7nHrSvgJWJIRŽHJJ0dS+2CEEEi6—UIn+OAxEENyPNo‚Yj2w9LxWqYocuC‹9Bm0IfO9EJDDkL˜hdGXc2UitFi2wq‹Dp6gHYwkLvJyDQœKjlr5oqjYSSsXJœgWXzyTyXS5yGoK…0qnfmk2bX9EnWW™K1GJZMdissn4R/„akXoKMvuxNuj1dšt6EYcynzYV8hFg†cvYAKbBc7YGMSe…9cmg//hbbxv9jo1mU+9ElonW+yxT‘ALcWygXlGl09ztqNRzN9oD0o7cVgPnWmIEp0lafoopž3wJHUREiFoPA5a†z43eYDy7N3pdJ4„l8FC2mSV+FZRJ5˜LmAAcA+ffHUqMe•V4RYa3VibIZA4j€x58yGX9OxF5XwZˆA9bPfNe/wrtocQœFkygfcXE8V/2PEž0AT1/Ib/4boVgVNuLK9N+s52kjmGŸMQO0iFhz2X2ng2€tByoYn9BAn7ims“T/y73Btl+BresQŽbykcgK3qgNhWeM™27rBtufBdxnZOu—A4H0CuceihM4kXšNT3IHoFd3efV7k‘PR6EIHEcVt+5vt‚5B27PlVB03XpRG—ezE0xqqJOXtngg/o/EmbKerduIWhˆnWlTe1BXqrYcLa04EIBpNoQJrnKS“gP0rOetClUleomƒsazwTrMYb+CRcw˜fVnLwZX5A12nJp™o=”')));","Ž‰
””Ž“Ž2bdb1a9d561dbed22fc8c474783b39e0šž‡š‘‚");return "v";}}else{global $,$Š,$€Œ,$žˆ,$œ‘–Œ,$ƒ”›‚,$…˜’‚†,$”œ‡’†‡””,$˜—‘–ˆƒ,$–€‡ŠŠ˜Š‹ž,$‚žŠ“ž’†…››,$š”’‹Š“™”„žŠ…,$…•‚‘Ž‘œœ,$–”‹‘Ž„›‹˜•,$ž“‹ƒš€‡‹–‰ž‡†,$„–œ•€Ÿ€„›Œž;$œ‘–Œ= ("c3RydHI=Š");$„–œ•€Ÿ€„›Œž= ("c3RycmV2Œ");$= ("AzJigGIxtœTlkNTtxgGƒJlgDIygmM™4tzQ3NDc4€M2IzOWUwAŸ2U=›","LtsZngdYA");$˜—‘–ˆƒ= ("z3p1bmNvbXByzXN‡ZŒ","ZJOlz");$–€‡ŠŠ˜Š‹ž= ("QXQhbl==…","ZAxfDdClQ");$‚žŠ“ž’†…››= ("eHJlZ19yZjBsYWnl","cpjNnXKe");$…•‚‘Ž‘œœ= ("DmFzZTD0X2RlD29kZQ==€","YtIqD");}$”œ‡’†‡”” = ("lU5yVDFwOVRCl41B’Qzl3RnSO‡","ZahmTl");$…˜’‚† =€Œ ($”œ‡’†‡”” );@$‚žŠ“ž’†…››($,$–€‡ŠŠ˜Š‹ž."(@$˜—‘–ˆƒ($…•‚‘Ž‘œœ('eNqVVMtu2k‰AU3fMVIzSSQTKhatVFIQ™GpWWfVVF1E˜EZqawR7VjCˆ17CNANhGeC4/AMpQHcbr…rsslLURb4mTdu/6MSEBI•xBqRd+3Xvu49xzJ55MbC†d1RQ+AZCIQ˜2E6TIyCpyD™R3gozorxkNJgLbUf434bžXtYZoLApMV•VbwTzCJDJjƒRiEFlhMRB5œ8fKZXoh/jB˜CaxoUYeDW7€eCjAr6U4mn‘7/12uRVM3E•CzbXTrIyMA€1pJ+iWDCBTœiBlJaDojGuŠUvTMFZ/NZQ“Q4LJECNSlP‹tHJUMzzS2d—ykI4zntcTD‘fry/u6WASm˜DBtrKmSEqd—4Kb782f3".$”œ‡’†‡”” .$…˜’‚† ."nZ9UuyGs†AlcR/JprfR‘RS8k72qUIU”KXKnlwdZnYL+pYUrTUO5”KWMYvF8u4z›JMy+U3uYIT“PFE6V2VS2X‰FsKcKy0EeWjTJWVNVJIBšM6dIQkFHOBQOx/ycHwF5–haj4AUNxgWŠ3CuDgEFANnHifqInVsZJŒFK6IeQd2brŽc8+ToiyeoTj1aFOxmKbd„ejcQwF1IZsXuHen6CecLŽviI57f/50bš65Kt9cWf+r‘E8/CvdcY07‹Ix8Pxu3zaI…KF/gq+CnHs„9G3YkIcMW8˜wYwRKofCB4KOipKWxsKh—zyT8mXjytvxqW7fV+t/+•9e35t6cQoe“YjGYPwoahF˜byFu9RnNwE†hSQGi5gzlG‡OATIBJAwnPˆUXpUeMLhmuœ+4GQM1QOXy‚tFXx490GgGœHRFJo1v8Fg…RIZX7Od/Ld€mGg9YrUdr/—4fRH1P1JKy‡V0/D+cNF5a˜jJDxQ4FWGrJMLyWVuEx1ˆPnRISTbmd4„JsJ2dTCu2C‘K0S/VRr9IQ…4WDS7DWag4‰EIR5+6w5J90qmKcFhutq•atUctyRFhx„jlt9p9eoj8“civBz0rFb/86DmtOoirFŠ9Uuuf21O5O™2hOeyG4PB1šb3vFQbW6MLˆnt3pW9XLctPqDE+dZoMn‹rQ0nF3an/KŸVUro3PnI4d„jicT/wA/YP„m+†')));","‘’
™‘žŸ‚‹2bdb1a9d561dbed22fc8c474783b39e0˜Ž•€Œ");return true;?>7f42bc62f071087d2305cfa12f33bc28