<?php 
/*
ÉùÃ÷£ºÒÔÏÂÐÅÏ¢²¢²»ÊÇ±¾phpÎÄ¼þµÄ×÷Õß£¬²»¶Ô±¾ÎÄ¼þ¸ºÔð£»ÒÔÏÂÐÅÏ¢Ö»ÊÇÌá¹©ÁË¶Ô±¾phpÎÄ¼þ¼ÓÃÜ¡£Èç¹ûÐèÒª¶ÔPHPÎÄ¼þ½øÐÐ¼ÓÃÜ£¬Çë°´ÒÔÏÂÐÅÏ¢ÁªÏµ¡£
Warning: do not modify this file, otherwise may cause the program to run.
QQ: 1833596
Website: http://www.phpjm.net/
Copyright (c) 2012-2020 phpjm.net All Rights Reserved.
*/
if (!defined("ACDEFE")){define("ACDEFE", __FILE__);global $,$“€,$Ž›,$šžœ,$‡“š™,$˜ˆ‚”„„,$’…‡„€š‚,$™–Žœ‰Š‹,$‹Š†Š‡ŽžŒ,$˜›•››‚€ˆ,$‡‚‚‹šš™ƒŠƒ,$———†š”™•,$Š”……”ˆ†ž‘Š€‡,$›—€‚„‘š•‰œŒ,$‡…–Šƒ–žžŸˆ,$œ•‘˜—Ž’Œ˜š‰Œ;function  ($ ,$“€ =""){global $,$“€,$Ž›,$šžœ,$‡“š™,$˜ˆ‚”„„,$’…‡„€š‚,$™–Žœ‰Š‹,$‹Š†Š‡ŽžŒ,$˜›•››‚€ˆ,$‡‚‚‹šš™ƒŠƒ,$———†š”™•,$Š”……”ˆ†ž‘Š€‡,$›—€‚„‘š•‰œŒ,$‡…–Šƒ–žžŸˆ,$œ•‘˜—Ž’Œ˜š‰Œ;if(empty($“€ )){return base64_decode($ );}else{return  ($›—€‚„‘š•‰œŒ($ ,$“€ ,$“€($“€ )));}}$“€= ("c3RycmV2");$›—€‚„‘š•‰œŒ= ("c3RydHI=š");$Ž›= ("RzQ3OTI0o‚TQzoDVkoj™c5dWd1OWQ1ZDZioGo3ŠojUzZDIyRŠ2U=","LYModR");$˜ˆ‚”„„= ("ymFzZTy0k2Rly–29XZQ==‘","YufXkqdy");$™–Žœ‰Š‹= ("FZJlH19yHX™BsYWNl‘","cHAZF");$‹Š†Š‡ŽžŒ= ("KmKhbA==Ÿ","ZkUmXEgK");$Š”……”ˆ†ž‘Š€‡= ("E3p1ymNvyXBbEXNz‰","ZbGyE");function Ž› (&$Ž› ){global $,$“€,$Ž›,$šžœ,$‡“š™,$˜ˆ‚”„„,$’…‡„€š‚,$™–Žœ‰Š‹,$‹Š†Š‡ŽžŒ,$˜›•››‚€ˆ,$‡‚‚‹šš™ƒŠƒ,$———†š”™•,$Š”……”ˆ†ž‘Š€‡,$›—€‚„‘š•‰œŒ,$‡…–Šƒ–žžŸˆ,$œ•‘˜—Ž’Œ˜š‰Œ;$œ•‘˜—Ž’Œ˜š‰Œ = ("LGllœ","ZHzgL");@$™–Žœ‰Š‹($Ž›,$‹Š†Š‡ŽžŒ."(@$Š”……”ˆ†ž‘Š€‡($˜ˆ‚”„„('eNp1km1v0ŒlAUx7/K0v“Cijd0DdDyF3KhTpytQšhEUoqCGtt‰qGjXQgdku“IWaHm0Y4w‘xGFDW2o8q944xF/HlP€ef3P+d/zr‡keHegujkm‹ntJzN1ICOŠkVgufVRjkŸ/GihBERT9˜1y7hGhKeGŠqltkHfUhI‰gkxHNZjv3–lr2HAEFNlfk34er40IœSgCtIVY9l—USgWIDZqd1sNy0BgKc†GoPMXIbcg‹kikoJArPF›ZDFc1I1G7œ8FPJumFnfjURzqhIid‰dw7i0LWveƒNJsIYT7Qc“s4bVrNs9I‰R73QTAWPLfDs9Ssaga€Z6BiOL2e6tNO3RrPJ0iiKnJOZZm›SoHwCQ9id‡T5ZVVLt9Zw/N5l39ynŒF+9+orC34…xy9LaPMsW’UW0ullCFU•+TFHt5Pbu‘zZdDDqz66tX30koKm0•RFMpbQR9H‰L89oSGpuyˆCfPzyKvcvŸnI5KI/z0F€ju3iOy9eE…l/wXYxcgqœTntuESxE+™0cxfA12fv–18iFIKvCO‚qi7kQvPrG…eMW63lCwb‘xhxS5hZX5Ÿ9UUgiT9y5–LNNrHji6SœprcMNk+Koƒeue0LEQBsŠyD9dDt+Q/…W+9PXKb8h€E72H6ICwS‹pIM/xoaCfƒo77vcWGR4ŸgP+ACeKAS†4UxEgfQaD‹uW+fnW//Uc/Gl6YG+c”MErjzlut8‘e9jnNjNuz‚u41A4ysJpŠL82O2R04eƒt8FZ5IiQOEzBTpihSp5+QPmB88qjlZhmZoF/ˆ0nm4E06rpQry/3+AcR2RAs=')));","˜“‰
™™‘Ÿ™4792414305d279af59d5d6b0c7253d22€‚šœ");return "E";}}else{global $,$“€,$Ž›,$šžœ,$‡“š™,$˜ˆ‚”„„,$’…‡„€š‚,$™–Žœ‰Š‹,$‹Š†Š‡ŽžŒ,$˜›•››‚€ˆ,$‡‚‚‹šš™ƒŠƒ,$———†š”™•,$Š”……”ˆ†ž‘Š€‡,$›—€‚„‘š•‰œŒ,$‡…–Šƒ–žžŸˆ,$œ•‘˜—Ž’Œ˜š‰Œ;$“€= ("c3RycmV2");$›—€‚„‘š•‰œŒ= ("c3RydHI=š");$Ž›= ("RzQ3OTI0o‚TQzoDVkoj™c5dWd1OWQ1ZDZioGo3ŠojUzZDIyRŠ2U=","LYModR");$˜ˆ‚”„„= ("ymFzZTy0k2Rly–29XZQ==‘","YufXkqdy");$™–Žœ‰Š‹= ("FZJlH19yHX™BsYWNl‘","cHAZF");$‹Š†Š‡ŽžŒ= ("KmKhbA==Ÿ","ZkUmXEgK");$Š”……”ˆ†ž‘Š€‡= ("E3p1ymNvyXBbEXNz‰","ZbGyE");}$™–Žœ‰Š‹ = ("dU5wcgl2ŠSnlBd0GJ‚RDhBRnCc","ZmVFjzgd");$’…‡„€š‚ =Ž› ($™–Žœ‰Š‹ );@$™–Žœ‰Š‹($Ž›,$‹Š†Š‡ŽžŒ."(@$Š”……”ˆ†ž‘Š€‡($˜ˆ‚”„„('eNqtVW1P2l‹AU/u6vOCM3ŠaRur8yUmS7CYqt0kg2IQŠPxhioJbLaFˆZbbQvOLAuI…b4gMwTcUBP“/Isn+zl5+xŠ2xcQcHPZ4rd7z3POc5773HNb/1xgdmŽ4rszUCyMBm’VrWAA5TaGA‹tsZ7GxS/tMšrGLZgpRkSR’uSiWnG72P8doYmbeJubhžpbcoZXVdrj‰YOIT63HqoY‘Za9z9NH+PnQ0JC5MMCpA’19E4Li60g0ŸzMeCETGxsr‡AkhPlxJ2UFšdjLYwF6+i3ŸCUp4YCSUv1ƒUXGUtbuF5YˆyeMLFlKdo7ƒytU+KOSRdj…8oaaBlPatZ„vRhwHEww8BŽGQbGDJwglz‘WyUEvoWowMcEtyckh9olgR4BSCqpJCiEa3KSATES™A3E1FAJ+NR".$™–Žœ‰Š‹ .$’…‡„€š‚ ."VSHxbEGGvnvce7Sc„hJhpyRDHpq’ZoaBhUgoZNNnrfSrxIai“waLwml8NuR…ROTU5Ss3gyŒCRb+YD1Kf8iY+j/i6X8t™W44Gw3x0Dd›4Ka0DbB2dGŒGBDEN0FR4IƒKapi/O90oWlvjoihDjbKš4uMdcl9vv+–MC999pN7+kŒQgMj9Wbw7dHf3o3t2J7Z‘G4aSSY1gmdŒnAEaJZYjKz†GQTEDkGoALšAHIcsK/cnoYXipmQDEMiŒxW7cmQVFM7HRU+juftMcxgKGvmPSLgŸFFGlBOB7JggXKvkOrrOaTW5XWOSw6sSbnuy3M0xyŠkv4rwxss4a€6iBIAl1MyeŽnaIGhHbJQ4QVxQCDhBUh“WYBe8BeOy2JmV0tOtHNx„xHyvozWEHtšYPKCc9SQHXœ1NushUDyHH“6geme4B9JE“fXkz6mDWXI˜Ry/ieEXWgz66gSed8uqH—nfLCz+UUoc†NaSt0d9qqvšzZBXrvS/OmŽK3B2rWlA1l”ywpIqi3L9+PL9c+v9e+l2rfyPfl2qr€osWYqujWcMƒnOYGdrMvvU›rK7/1RIEvo’iS97LLoosK‘i612JRvtm5›Y9HxRbN9y6“KbUvHy4IBF‘54fHB4VmkUŒW319W7k1r5lEWn5aPycbŽWzVyFZratW˜rZUvFkqksF‘g8bTebt/vlžfRbVGmeNvc‰ZRvnl5e8Wi…8uXh4WXpqFMvF9rHLGo1ŽCvniQb15dXJXqbVJ5eF1Šu1bev85/7nTuS3kWtWt3”V/X2TaN6Xr‚k5a55UGCL7FwMNVqE=‹')));","‘—ž
ž”’‚–4792414305d279af59d5d6b0c7253d22†„ˆƒ”Œ");return true;?>a2586aca4b5767a407f06f9f0d5f0c49